/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'

import { useGLTF } from '@react-three/drei'

const Model = props => {
  const { nodes, materials } = useGLTF('/models/city/city-diy.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portal_gate.geometry}
        material={materials['Dark rock']}
        position={[0, 2.399, -40.15]}
        scale={[4.745, 4.745, 1.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portal_vortex.geometry}
        material={materials['Portal vortex']}
        position={[0, 3.171, -40.69]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[3.706, 3.706, 3.142]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.River.geometry}
        material={materials.River}
        position={[20.263, -0.125, -40.527]}
        scale={[0.038, 0.047, 0.047]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge.geometry}
        material={materials.Wood}
        position={[17.83, 0.426, -16.279]}
        rotation={[0, 0.375, 0]}
        scale={[5.965, 3.117, 3.117]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shop_counter.geometry}
        material={materials.Counter}
        position={[-38.323, 3.823, -13.368]}
        rotation={[0, 1.571, 0]}
        scale={1.132}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trainer_counter.geometry}
        material={materials.Counter}
        position={[-30.61, 3.801, -26.208]}
        scale={1.132}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Infirmary_counter.geometry}
        material={materials.Counter}
        position={[23.89, 1.164, 12.168]}
        rotation={[0, -0.813, 0]}
        scale={1.132}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mercenaries_counter.geometry}
        material={materials.Counter}
        position={[24.933, 1.141, -24.666]}
        rotation={[0, 0.014, 0]}
        scale={1.132}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Quest_counter.geometry}
        material={materials.Counter}
        position={[8.615, 1.082, -36.707]}
        rotation={[0, -0.461, 0]}
        scale={1.132}
      />
      <mesh geometry={nodes.Plane006.geometry}>
        <meshLambertMaterial color="green" />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006_1.geometry}
        material={materials.Sand}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006_2.geometry}
        material={materials.Ciment}
      />
    </group>
  )
}

useGLTF.preload('/models/city/city-diy.glb')

export default Model
