/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 forest.glb --transform -t 
Files: forest.glb [46.84KB] > /Users/verekia/Local/Code/r3f-rpg/public/models/forest/forest-transformed.glb [4.87KB] (90%)
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

import { pi } from '#/lib/util'

type GLTFResult = GLTF & {
  nodes: {
    Ground: THREE.Mesh
  }
  materials: {
    Palette: THREE.MeshStandardMaterial
  }
}

const path = '/models/forest/forest-transformed.glb'

const ForestModel = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(path) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Ground.geometry}
        material={materials.Palette}
        scale={9}
        position-x={-1}
        rotation-y={pi / 3}
      />
    </group>
  )
}

useGLTF.preload(path)

export default ForestModel
